---
sidebar: sidebar 
permalink: reference-limits-aws.html 
keywords: limits, maximum, storage, aggregates, disks, volumes, capacity, luns, size, storage virtual machine, SVM, ebs 
summary: Cloud Volumes ONTAP ha limiti di configurazione dello storage in AWS per fornire operazioni affidabili. Per ottenere prestazioni ottimali, non configurare il sistema ai valori massimi. 
---
= Limiti di storage in AWS
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Volumes ONTAP ha limiti di configurazione dello storage per garantire operazioni affidabili. Per ottenere prestazioni ottimali, non configurare il sistema ai valori massimi.



== Capacità massima del sistema per licenza

La capacità massima del sistema per un sistema Cloud Volumes ONTAP è determinata dalla relativa licenza. La capacità massima del sistema include lo storage basato su disco e lo storage a oggetti utilizzato per il tiering dei dati. NetApp non supporta il superamento di questo limite.

Per alcune configurazioni ha, i limiti dei dischi impediscono di raggiungere il limite di capacità utilizzando solo i dischi. In questi casi, è possibile raggiungere il limite di capacità di https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-data-tiering.html["tiering dei dati inattivi sullo storage a oggetti"^]. Per ulteriori informazioni, fare riferimento ai limiti di capacità e dischi riportati di seguito.

[cols="25,75"]
|===
| Licenza | Capacità massima del sistema (dischi + storage a oggetti) 


| Freemium | 500 GiB 


| ESPLORAZIONE DI PAYGO | 2 TIB (il tiering dei dati non è supportato con Explore) 


| Standard PAYGO | 10 TIB 


| PAYGO Premium | 368 TIB 


| Licenza basata su nodo | 2 PIB (richiede più licenze) 


| Licenza basata sulla capacità | 2 PIB 
|===
.Per ha, il limite di capacità della licenza è per nodo o per l'intera coppia ha?
Il limite di capacità è per l'intera coppia ha. Non è per nodo. Ad esempio, se si utilizza la licenza Premium, è possibile avere fino a 368 TIB di capacità tra entrambi i nodi.

.Per un sistema ha in AWS, i dati mirrorati vengono conteggiati rispetto al limite di capacità?
No, non è così. I dati di una coppia ha AWS vengono sottoposti a mirroring sincrono tra i nodi in modo che siano disponibili in caso di guasto. Ad esempio, se si acquista un disco 8 TIB sul nodo A, Cloud Manager alloca anche un disco 8 TIB sul nodo B che viene utilizzato per i dati mirrorati. Sebbene sia stato eseguito il provisioning di 16 TIB di capacità, solo 8 TIB sono contati rispetto al limite di licenza.



== Limiti di dischi e tiering per istanza EC2

Cloud Volumes ONTAP utilizza i volumi EBS come dischi, con una dimensione massima del disco di 16 TIB. Le sezioni seguenti mostrano i limiti di dischi e tiering in base al tipo di istanza EC2, in quanto molti tipi di istanze EC2 hanno limiti di dischi diversi. I limiti dei dischi sono anche diversi tra i sistemi a nodo singolo e le coppie ha.

I limiti dei dischi riportati di seguito sono specifici per i dischi che contengono dati utente. I limiti non includono il disco di boot e il disco root.

* Puoi acquistare più licenze basate su nodi per un sistema Cloud Volumes ONTAP BYOL a nodo singolo o coppia ha, per allocare più di 368 TiB di capacità, fino al limite massimo di capacità di sistema testato e supportato di 2 PIB. Tenere presente che i limiti dei dischi possono impedire di raggiungere il limite di capacità utilizzando solo i dischi. È possibile superare il limite di dischi di https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-data-tiering.html["tiering dei dati inattivi sullo storage a oggetti"^]. https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-manage-node-licenses.html["Scopri come aggiungere ulteriori licenze di sistema a Cloud Volumes ONTAP"^]. Sebbene Cloud Volumes ONTAP supporti fino alla capacità massima testata e supportata di sistema di 2 PIB, il superamento del limite di 2 PIB comporta una configurazione di sistema non supportata.
+
** Il cloud segreto e le regioni del cloud top secret AWS supportano l'acquisto di licenze basate su nodi multipli a partire da Cloud Volumes ONTAP 9.12.1.






=== Nodo singolo con licenza Premium

[cols="18,18,32,32"]
|===
| Famiglia di istanze | Numero massimo di dischi per nodo | Capacità massima del sistema con i soli dischi | Capacità massima del sistema con dischi e tiering dei dati 


| istanze c5, m5 e r5 | 22 | 352 TIB | 368 TIB 


| istanze c4, m4 e r4 | 34 | 368 TIB | 368 TIB 
|===


=== Nodo singolo con licenze basate su nodo

[cols="18,18,16,16,16,16"]
|===
| Famiglia di istanze | Numero massimo di dischi per nodo 2+| Capacità massima del sistema con una licenza 2+| Capacità massima del sistema con più licenze 


2+|  | *Dischi da soli* | *Dischi + tiering dei dati* | *Dischi da soli* | *Dischi + tiering dei dati* 


| istanze c5, m5 e r5 | 22 | 352 TIB | 368 TIB | 352 TIB | 2 PIB 


| istanze c4, m4 e r4 | 34 | 368 TIB | 368 TIB | 544 TIB | 368 TIB x ogni licenza 
|===


=== Nodo singolo con licenze basate sulla capacità

[cols="18,18,32,32"]
|===
| Famiglia di istanze | Numero massimo di dischi per nodo | Capacità massima del sistema con i soli dischi | Capacità massima del sistema con dischi e tiering dei dati 


| istanze c5, m5 e r5 | 22 | 352 TIB | 2 PIB 


| istanze c4, m4 e r4 | 34 | 544 TIB | 2 PIB 
|===


=== HA si accoppia con una licenza Premium

[cols="18,18,32,32"]
|===
| Famiglia di istanze | Numero massimo di dischi per nodo | Capacità massima del sistema con i soli dischi | Capacità massima del sistema con dischi e tiering dei dati 


| istanze c5, m5 e r5 | 19 | 304 TIB | 368 TIB 


| istanze c4, m4 e r4 | 31 | 368 TIB | 368 TIB 
|===


=== HA si accoppia con licenze basate su nodo

[cols="18,18,16,16,16,16"]
|===
| Famiglia di istanze | Numero massimo di dischi per nodo 2+| Capacità massima del sistema con una licenza 2+| Capacità massima del sistema con più licenze 


2+|  | *Dischi da soli* | *Dischi + tiering dei dati* | *Dischi da soli* | *Dischi + tiering dei dati* 


| istanze c5, m5 e r5 | 19 | 304 TIB | 368 TIB | 304 TIB | 2 PIB 


| istanze c4, m4 e r4 | 31 | 368 TIB | 368 TIB | 496 TIB | 368 TIB x ogni licenza 
|===


=== HA si accoppia con licenze basate sulla capacità

[cols="18,18,32,32"]
|===
| Famiglia di istanze | Numero massimo di dischi per nodo | Capacità massima del sistema con i soli dischi | Capacità massima del sistema con dischi e tiering dei dati 


| istanze c5, m5 e r5 | 19 | 304 TIB | 2 PIB 


| istanze c4, m4 e r4 | 31 | 496 TIB | 2 PIB 
|===


== Limiti aggregati

Cloud Volumes ONTAP utilizza i volumi AWS come dischi e li raggruppa in _aggregati_. Gli aggregati forniscono storage ai volumi.

[cols="2*"]
|===
| Parametro | Limite 


| Numero massimo di aggregati | Nodo singolo: Uguale alle coppie ha limite disco: 18 in un nodo ^1^ 


| Dimensione massima dell'aggregato | 96 TIB di capacità raw ^2^ 


| Dischi per aggregato | 1-6 ^3^ 


| Numero massimo di gruppi RAID per aggregato | 1 
|===
Note:

. Non è possibile creare 19 aggregati su entrambi i nodi in una coppia ha, in quanto ciò supererebbe il limite del disco dati.
. Il limite di capacità aggregata si basa sui dischi che compongono l'aggregato. Il limite non include lo storage a oggetti utilizzato per il tiering dei dati.
. Tutti i dischi di un aggregato devono avere le stesse dimensioni.




== Limiti di storage logico

[cols="22,22,56"]
|===
| Storage logico | Parametro | Limite 


| *Storage VM (SVM)* | Numero massimo di Cloud Volumes ONTAP (coppia ha o nodo singolo)  a| 
*Istanze C5, M5 e R5 con BYOL* il seguente numero di storage VM è supportato con i tipi di istanze C5, M5 e R5 quando si porta la propria licenza (BYOL):

* 12 VM storage con sistemi a nodo singolo
* 8 VM storage con coppie ha



NOTE: Una VM di storage copre l'intero sistema Cloud Volumes ONTAP (coppia ha o nodo singolo)

È necessaria una licenza add-on per ogni SVM _data-serving_ aggiuntiva oltre la prima VM storage fornita con Cloud Volumes ONTAP per impostazione predefinita. Contattare il proprio account team per ottenere una licenza add-on SVM.

Le VM di storage configurate per il disaster recovery (DR) non richiedono una licenza add-on (sono gratuite), ma contano rispetto al limite delle VM di storage. ^1,2^

*Tutte le altre configurazioni* sono supportate una VM di storage per il servizio dati e una VM di storage di destinazione utilizzate per il disaster recovery. ^2^

Una VM di storage copre l'intero sistema Cloud Volumes ONTAP (coppia ha o nodo singolo).



.2+| *File* | Dimensione massima | 16 TIB 


| Massimo per volume | In base alle dimensioni del volume, fino a 2 miliardi 


| *Volumi FlexClone* | Profondità del clone gerarchico ^3^ | 499 


.3+| *Volumi FlexVol* | Massimo per nodo | 500 


| Dimensione minima | 20 MB 


| Dimensione massima | 100 TIB 


| *Qtree* | Massimo per volume FlexVol | 4,995 


| *Copie Snapshot* | Massimo per volume FlexVol | 1,023 
|===
Note:

. Ad esempio, se si dispone di 8 VM di storage che servono dati su una coppia ha, il limite è stato raggiunto e non è possibile creare altre VM di storage. Lo stesso vale per un'altra coppia ha con 8 VM di storage configurate per il disaster recovery: Hai raggiunto il limite e non puoi creare altre VM di storage.
. È possibile attivare una VM di storage di destinazione per l'accesso ai dati in caso di interruzione della VM di storage di origine. Cloud Manager non fornisce alcun supporto di configurazione o orchestrazione per il disaster recovery delle macchine virtuali dello storage. È necessario utilizzare System Manager o la CLI.
+
** https://library.netapp.com/ecm/ecm_get_file/ECMLP2839856["Guida rapida alla preparazione del disaster recovery per SVM"^]
** https://library.netapp.com/ecm/ecm_get_file/ECMLP2839857["Guida di SVM Disaster Recovery Express"^]


. La profondità dei cloni gerarchici è la profondità massima di una gerarchia nidificata di volumi FlexClone che è possibile creare da un singolo volume FlexVol.




== Limiti dello storage iSCSI

[cols="3*"]
|===
| Storage iSCSI | Parametro | Limite 


.4+| *LUN* | Massimo per nodo | 1,024 


| Numero massimo di mappe LUN | 1,024 


| Dimensione massima | 16 TIB 


| Massimo per volume | 512 


| *igroups* | Massimo per nodo | 256 


.2+| *Iniziatori* | Massimo per nodo | 512 


| Massimo per igroup | 128 


| *Sessioni iSCSI* | Massimo per nodo | 1,024 


.2+| *LIF* | Massimo per porta | 32 


| Massimo per portset | 32 


| *Portset* | Massimo per nodo | 256 
|===